version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
      - "4467:4467"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    image: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis # ensures that redis is a host that the container can find
      - prisma
    depends_on:
      - redis
      - prisma
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_AUTH_DURATION=${JWT_AUTH_DURATION}
      - JWT_REFRESH_DURATION=${JWT_REFRESH_DURATION}
      - PRISMA_HOST=prisma
      - REDIS_HOST=redis
      - EMAIL=${EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
volumes:
  postgres:
